import { Language } from './type';

const persian: Language = {
    global: {},
    status: {
        connecting: 'درحال اتصال ...',
        connected: 'اتصال برقرار شد',
        connected_confirm: 'متصل هستید',
        disconnecting: 'قطع ارتباط ...',
        disconnected: 'متصل نیستید',
        ip_check: 'دریافت اطلاعات ...',
        keep_trying: 'جهت تکرار تلاش، کمی صبر کنید ...'
    },
    home: {
        title_warp_based: 'بر پایه وارپ',
        drawer_settings_warp: 'تنظیمات وارپ',
        drawer_settings_routing_rules: 'قوانین مسیریابی',
        drawer_settings_app: 'تنظیمات برنامه',
        drawer_settings_scanner: 'تنظیمات اسکنر',
        drawer_settings_network: 'تنظیمات شبکه',
        drawer_log: 'لاگ برنامه',
        drawer_update: 'بروزرسانی',
        drawer_update_label: 'نسخه جدید',
        drawer_speed_test: 'تست سرعت',
        drawer_about: 'درباره برنامه',
        drawer_lang: 'تغییر زبان',
        drawer_singbox: 'تنظیمات تانل'
    },
    toast: {
        ip_check_please_wait: 'برای بررسی مجدد چندثانیه دیگر تلاش کنید!',
        ir_location:
            'کلودفلر به یک IP با لوکیشن ایران که متفاوت از آیپی اصلیته وصلت کرده که باهاش میتونی فیلترینگ‌رو دور بزنی، اما تحریم‌هارو نه. نگران نباش! در تنظیمات میتونی توسط گزینه «گول» یا «سایفون» لوکیشن رو تغییر بدی.',
        btn_submit: 'متوجه شدم',
        copied: 'کپی شد!',
        cleared: 'لاگ پاکسازی شد!',
        please_wait: 'کمی صبر کنید ...',
        offline: 'به اینترنت متصل نیستید!',
        settings_changed: 'اعمال تنظیمات نیازمند اتصال مجدد می\u200Cباشد.',
        hardware_usage: 'فعال نگه‌داشتن این‌گزینه موجب افزایش مصرف منابع سخت‌افزار می‌گردد.',
        config_added: 'کانفیگ به درستی اضافه شده و برای استفاده از آن باید بر روی اتصال بزنید.',
        profile_added: 'اندپوینت به درستی به پروفایل اضافه شد.',
        endpoint_added: 'اندپوینت به درستی جایگزین شد.'
    },
    settings: {
        title: 'تنظیمات وارپ',
        more: 'سایر تنظیمات',
        method_warp: 'وارپ',
        method_warp_desc: 'فعالسازی Warp',
        method_gool: 'گول',
        method_gool_desc: 'فعالسازی WarpInWarp',
        method_psiphon: 'سایفون',
        method_psiphon_desc: 'فعالسازی Psiphon',
        method_psiphon_location: 'انتخاب کشور',
        method_psiphon_location_auto: 'Random',
        method_psiphon_location_desc: 'انتخاب آی\u200Cپی کشور موردنظر',
        endpoint: 'اندپوینت',
        endpoint_desc: 'ترکیبی از IP یا نام دامنه، به\u200Cهمراه پورت',
        license: 'لایسنس',
        license_desc: 'لایسنس ۲ برابر مصرف می‌شود',
        option: 'تنظیمات برنامه',
        network: 'تنظیمات شبکه',
        proxy_mode: 'پیکربندی',
        proxy_mode_desc: 'انتخاب نحوه تنظیم پروکسی',
        port: 'پورت پروکسی',
        port_desc: 'تعیین پورت پروکسی برنامه',
        share_vpn: 'اتصال از LAN',
        share_vpn_desc: 'اشتراک\u200Cگذاری پروکسی بر روی شبکه',
        dns: 'انتخاب DNS',
        dns_desc: 'محدودسازی تبلیغات و محتوای بزرگسال',
        dns_error: 'برای متدهای Warp و Gool کاربرد دارد',
        ip_data: 'بررسی IP',
        ip_data_desc: 'نمایش آی\u200Cپی و لوکیشن پس\u200Cاز اتصال',
        data_usage: 'مصرف داده',
        data_usage_desc: 'نمایش لحظه‌ای سرعت و مصرف داده',
        dark_mode: 'حالت تیره',
        dark_mode_desc: 'مشخص\u200Cکردن حالت نمایش برنامه',
        lang: 'زبان برنامه',
        lang_desc: 'تغییر زبان رابط کاربری برنامه',
        open_login: 'اجرای خودکار',
        open_login_desc: 'بازشدن هنگام روشن\u200Cشدن سیستم',
        auto_connect: 'اتصال خودکار',
        auto_connect_desc: 'متصل‌شدن هنگام بازشدن برنامه',
        system_tray: 'مخفی\u200Cسازی',
        system_tray_desc: 'قرار نگرفتن آیکون برنامه در تسک\u200Cبار',
        force_close: 'بستن اجباری',
        force_close_desc: 'با خروج در نوار اعلان قرار نگیرد',
        shortcut: 'پیمایشگر',
        shortcut_desc: 'میانبرها در صفحه نخست',
        restore: 'بازگردانی',
        restore_desc: 'اعمال تنظیمات پیشفرض برنامه',
        scanner: 'تنظیمات اسکنر',
        scanner_alert:
            'اسکنر درصورتی فعال می\u200Cشود که درحال استفاده از آدرس اندپوینت پیشفرض برنامه باشید.',
        scanner_ip_type: 'نوع اندپوینت',
        scanner_ip_type_auto: 'Automatic',
        scanner_ip_type_desc: 'جهت یافتن IP اندپوینت',
        scanner_rtt: 'وقفه زمانی',
        scanner_rtt_default: 'Default',
        scanner_rtt_desc: 'تعیین میزان RTT',
        scanner_reserved: 'رزرو',
        scanner_reserved_desc: 'استفاده از Reserved سفارشی وایرگارد',
        routing_rules: 'لیست سیاه',
        routing_rules_desc: 'جلوگیری از عبور ترافیک از وارپ',
        routing_rules_disabled: 'غیرفعال',
        routing_rules_items: 'مورد',
        profile: 'پروفایل',
        profile_desc: 'اندپوینت‌های ذخیره‌شده توسط شما',
        singbox: 'تنظیمات سینگ‌باکس',
        close_singbox: 'توقف عملیات',
        close_singbox_desc: 'بستن خودکار سینگ‌باکس هنگام لغو اتصال',
        close_helper: 'توقف دستیار',
        close_helper_desc: 'بستن خودکار دستیار هنگام خروج',
        mtu: 'مقدار MTU',
        mtu_desc: 'تعیین حداکثر واحد انتقال',
        geo_block: 'مسدودسازی',
        geo_block_desc: 'تبلیغات، بدافزار، فیشینگ و ماینرهای رمزارز',
        geo_rules_ip: 'مسیریابی IP',
        geo_rules_ip_desc: 'به‌کارگیری قوانین GeoIP',
        geo_rules_site: 'مسیریابی وب',
        geo_rules_site_desc: 'به‌کارگیری قوانین GeoSite',
        more_helper: 'تنظیمات دستیار',
        singbox_log: 'گزارش‌دهی',
        singbox_log_desc: 'تنظیم سطح Log',
        singbox_stack: 'چینش',
        singbox_stack_desc: 'تنظیم نوع Stack',
        singbox_sniff: 'تحلیل بسته‌ها',
        singbox_sniff_desc: 'فعالسازی Sniff و بازنویسی مقصد',
        more_duties: 'وظایف',
        beta_release: 'بروزرسانی بتا',
        beta_release_desc: 'اطلاع از نسخه‌های پیش‌ازانتشار'
    },
    tabs: {
        home: 'اتصال',
        warp: 'وارپ',
        network: 'شبکه',
        scanner: 'اسکنر',
        app: 'برنامه',
        singbox: 'سینگ‌باکس'
    },
    modal: {
        endpoint_title: 'اندپوینت',
        license_title: 'لایسنس',
        license_desc:
            'برنامه برای اجرا لزوماً به لایسنس وارپ نیاز نداشته، اما درصورت تمایل می\u200Cتوانید لایسنس خود را اینجا وارد کنید.',
        port_title: 'پورت پروکسی',
        license_clear: 'حذف',
        restore_title: 'بازگردانی تغییرات',
        restore_desc:
            'با تایید عملیات بازگردانی تغییرات، تمامی تنظیمات برنامه به\u200Cحالت پیشفرض بازگشته و اتصال شما قطع می\u200Cگردد.',
        routing_rules_sample: 'نمونه',
        routing_rules_alert_tun:
            'فقط قوانین مسیریابی domain, ip و app بر روی پیکربندی Tun اثرگذار خواهند بود.',
        routing_rules_alert_system:
            'به‌جز قانون مسیریابی app، سایر قوانین بر روی پیکربندی System Proxy اثرگذار هستند.',
        endpoint_default: 'پیشفرض',
        endpoint_suggested: 'پیشنهادی',
        endpoint_latest: 'اخیر',
        endpoint_update: 'دریافت اندپوینت‌های پیشنهادی',
        endpoint_paste: 'جایگذاری اندپوینت فعال',
        profile_title: 'پروفایل',
        profile_name: 'عنوان',
        profile_endpoint: 'اندپوینت',
        profile_limitation: (value) => `حداکثر می‌توانید ${value} اندپوینت اضافه نمایید.`,
        confirm: 'تایید می\u200Cکنم',
        mtu_title: 'مقدار MTU',
        mtu_desc:
            'حداکثر واحد انتقال یا MTU، به حداکثر اندازه بسته‌های داده اشاره دارد، که باید بین ۱۰۰۰ تا ۹۹۹۹ تنظیم شوند.',
        update: 'بروزرسانی',
        cancel: 'انصراف'
    },
    log: {
        title: 'لاگ برنامه',
        desc: 'درصورت ایجاد لاگ توسط برنامه، اینجا نمایش داده می\u200Cشود.',
        error_invalid_license: 'لایسنس وارد شده معتبر نیست؛ آن‌را حذف کنید.',
        error_too_many_connected: 'سقف استفاده از لایسنس پر شده؛ آن‌را حذف کنید.',
        error_access_denied: 'برنامه را به‌صورت Run as Administrator اجرا کنید.',
        error_failed_set_endpoint:
            'خطای تنظیم اندپوینت؛ مقدار آن‌را بررسی کرده یا دوباره تلاش کنید.',
        error_warp_identity: 'خطای احراز هویت در کلودفلر؛ دوباره تلاش کنید.',
        error_script_failed: 'برنامه با خطا مواجه شد؛ دوباره تلاش کنید.',
        error_object_null: 'برنامه با خطا مواجه شد؛ دوباره تلاش کنید.',
        error_port_already_in_use: (value) =>
            `پورت ${value} توسط برنامه دیگری درحال استفاده است؛ آن‌را تغییر دهید.`,
        error_port_socket: 'از یک پورت دیگر استفاده نمایید.',
        error_port_restart: 'پورت درگیر است؛ درحال راه‌اندازی مجدد ...',
        error_unknown_flag: 'یک دستور نادرست در پس‌زمینه اجرا شده است.',
        error_deadline_exceeded: 'مهلت اتصال پایان یافت؛ دوباره تلاش کنید.',
        error_configuration_encountered: 'پیکربندی پروکسی با خطا مواجه شد!',
        error_desktop_not_supported: 'محیط دسکتاپ پشتیبانی نمی‌شود!',
        error_configuration_not_supported:
            'پیکربندی پروکسی در سیستم عامل شما پشتیبانی نمی‌شود، اما می‌توانید به‌صورت دستی از پروکسی وارپ استفاده کنید.',
        error_configuring_proxy: (value) => `خطای پیکربندی پروکسی برای ${value}!`,
        error_wp_not_found: `فایل warp-plus در کنار بسته برنامه وجود ندارد!`,
        error_wp_stopped: `فایل warp-plus برای اجرا با مشکل مواجه است!`,
        error_connection_failed: 'اتصال به 1.1.1.1 امکان‌پذیر نبود.',
        error_country_failed: 'امکان اتصال به کشور انتخابی وجود ندارد.',
        error_singbox_failed_stop: 'متوقف‌کردن سینگ‌باکس با خطا مواجه شد!',
        error_singbox_failed_start: 'فعال‌کردن سینگ‌باکس با خطا مواجه شد!',
        error_wp_reset_peer: 'اتصال به کلودفلر به‌طور غیرمنتظره قطع شد!',
        error_failed_connection: 'اتصال موفقیت‌آمیز نبود!',
        error_canceled_by_user: 'عملیات توسط کاربر لغو شد.'
    },
    about: {
        title: 'درباره برنامه',
        desc: 'این\u200Cبرنامه یک نسخه غیررسمی، اما قابل اطمینان از اپ Oblivion یا فراموشی است که برای ویندوز، لینوکس و مک ارائه گردیده است.\nبرنامه Oblivion Desktop با الگو گرفتن از رابط کاربری نسخه اصلی که توسط یوسف قبادی برنامه\u200Cنویسی شده بود، با هدف دسترسی آزاد به اینترنت تهیه گردیده و هرگونه تغییر نام یا استفاده تجاری از آن مجاز نمی\u200Cباشد.',
        slogan: 'اینترنت برای همه، یا هیچ\u200Cکس!'
    },
    systemTray: {
        connect: 'اتصال',
        connecting: 'درحال اتصال ...',
        connected: 'متصل هستید',
        disconnecting: 'لغو اتصال ...',
        settings: 'تنظیمات',
        settings_warp: '   وارپ   ',
        settings_network: '   شبکه   ',
        settings_scanner: '   اسکنر   ',
        settings_app: '   برنامه   ',
        about: 'درباره',
        log: 'لاگ',
        speed_test: 'تست سرعت',
        exit: 'خروج'
    },
    update: {
        available: 'بروزرسانی جدید',
        available_message: (value) => `بروزرسانی جدیدی از ${value} در دسترس است. دریافت می‌کنید؟`,
        ready: 'دریافت شد',
        ready_message: (value) =>
            `برنامه ${value} برای آغاز فرایند بروزرسانی آماده است. راه‌اندازی شود؟`
    },
    speedTest: {
        title: 'تست سرعت',
        initializing: 'درحال آماده‌سازی ...',
        click_start: 'برای شروع تست کلیک کنید',
        error_msg: 'هنگام تست سرعت خطایی رخ داده؛ لطفا دوباره تلاش کنید.',
        server_unavailable: 'سرور تست سرعت در دسترس نیست',
        download_speed: 'سرعت دانلود',
        upload_speed: 'سرعت آپلود',
        latency: 'تاخیر',
        jitter: 'نوسان'
    }
};
export default persian;
