import { Language } from './type';

const myanmar: Language = {
    global: {},
    status: {
        connecting: 'ဆက်သွယ်နေသည် ...',
        connected: 'ချိတ်ဆက်ပြီး',
        connected_confirm: 'ချိတ်ဆက်ပြီး',
        disconnecting: 'ခွဲထွက်နေသည် ...',
        disconnected: 'ခွဲထွက်ပြီး',
        ip_check: 'IP စစ်ဆေးနေသည် ...',
        keep_trying: 'ကျေးဇူးပြု၍ ပြန်လည်ကြိုးစားရန် များစွာ စောင့်ဆိုင်းပါ ...',
        preparing_rulesets: 'Rulesets များကို ပြင်ဆင်နေသည်...',
        downloading_rulesets_failed: 'Rulesets များကို ဒေါင်းလုပ်လုပ်ခြင်း မအောင်မြင်ပါ။'
    },
    home: {
        title_warp_based: 'Warp အခြေခံ',
        drawer_settings_warp: 'Warp ဆက်သွယ်မှု',
        drawer_settings_routing_rules: 'Routing စည်းမျဉ်းများ',
        drawer_settings_app: 'အက်ပ်ကွက်ရင်း',
        drawer_settings_scanner: 'စကင်နာကွက်ရင်း',
        drawer_settings_network: 'ကွန်ယက်ကွက်ရင်း',
        drawer_log: 'အက်ပ်မှတ်တမ်း',
        drawer_update: 'အပ်ဒိတ်',
        drawer_update_label: 'အသစ် အပ်ဒိတ်',
        drawer_speed_test: 'မိုမိုအမြန်နှုန်း စမ်းသပ်ခြင်း',
        drawer_about: 'အက်ပ်အကြောင်း',
        drawer_lang: 'ဘာသာစကားပြောင်းလဲခြင်း',
        drawer_singbox: 'Tunnel ကွက်ရင်း'
    },
    toast: {
        ip_check_please_wait: 'IP စစ်ဆေးရန် ပြန်လည်ကြိုးစားရန် အချိန်ခဏ စောင့်ပါ!',
        ir_location:
            'Cloudflare သည် သင့်၏ အမှန်တရား IP နှင့် ကွာခြားသော မြောက်အီးရတ်နိုင်ငံအတွက် IP ဖြင့် ချိတ်ဆက်နေသည်။ ၎င်းကို များစွာတားဆီးခြင်းများကို ကျော်လွှားရန် အသုံးပြုနိုင်သည်။ ဒါပေမယ့်၊ အမှုဆောင်တာဝန်လည်း သတ်မှတ်နိုင်သည်။ သင့်တော်တယ်ဆိုလျှင် ဤကွက်ရင်းတွင် "Gool" သို့မဟုတ် "psiphon" ကို အသုံးပြု၍နေရာကို ပြောင်းလဲနိုင်ပါတယ်。',
        btn_submit: 'နားလည်ပါ',
        copied: 'ကူးယူပြီး!',
        cleared: 'မှတ်တမ်း ပစ်ခတ်ပြီး!',
        please_wait: 'ကျေးဇူးပြု၍ စောင့်ပါ ...',
        offline: 'သင်သည် အော့ဖလိုင်းဖြစ်နေပါသည်!',
        settings_changed: 'ပြင်ဆင်မှုများကိုလက်ခံရန် မရောက်တော့ပါ!',
        hardware_usage: 'ဤကွက်ရင်း ကို ဖွင့်ပါသည်။',
        config_added: 'အပ်ဒိတ် ပြောင်းလဲမှု ပြုလုပ်ခဲ့ပါသည်။',
        profile_added: 'နောက်ဆုံး လုပ်ဆောင်ထားသော End-point ၏ profile ဖွင့်နေပါသည်။',
        endpoint_added: 'Endpoint ရှင်းလင်းတယ်',
        new_update_notification: 'အသစ်သောဗားရှင်းအသစ်ရနိုင်ပါပြီ',
        new_update: 'အပ်ဒိတ်အသစ်ရနိုင်ပါသည်။ ဒေါင်းလုပ်ပြီး ထည့်သွင်းရန် ပြင်ဆင်လိုပါသလား။',
        up_to_date: 'သင်သည် အက်ပ်၏ နောက်ဆုံးဗားရှင်းကို အသုံးပြုနေပါသည်',
        exit_pending:
            'အက်ပ်သည် ထွက်ခွာခြင်းလုပ်ငန်းစဉ်ကို ပြီးဆုံးနေသည်။ ထပ်မံဖွင့်ရန် မပြုမီ ခဏစောင့်ပေးပါ။',
        help_btn: 'အကူအညီ'
    },
    settings: {
        title: 'Warp ဆက်တင်များ',
        more: 'ပိုပြီးဆက်တင်များ',
        method_warp: 'Warp',
        method_warp_desc: 'Warp ကိုဖွင့်ပါ',
        method_gool: 'Gool',
        method_gool_desc: 'WarpInWarp ကိုဖွင့်ပါ',
        method_masque: 'Masque',
        method_masque_desc: 'Masque ကို အသုံးပြုပါ',
        method_psiphon: 'Psiphon',
        method_psiphon_desc: 'Psiphon ကိုဖွင့်ပါ',
        method_psiphon_location: 'တိုင်းပြည်',
        method_psiphon_location_auto: 'စိတ်အလိုမရှိသော',
        method_psiphon_location_desc: 'လိုအပ်သောတိုင်းပြည် IP ကိုရွေးပါ',
        endpoint: 'အဆုံးသတ်ချက်',
        endpoint_desc: 'IP သို့မဟုတ် domain နာမည်နှင့် port ကိုပေါင်းစပ်ထားသည်',
        license: 'လိုင်စင်',
        license_desc: 'လိုင်စင်အသုံးပြုမှုသည်နှစ်ဆဖြစ်သည်',
        option: 'အက်ပလီကေးရှင်းဆက်တင်များ',
        network: 'ကွန်ယက်ဆက်တင်များ',
        proxy_mode: 'ကွန်ဖီဂျူးရေးရှင်း',
        proxy_mode_desc: 'Proxy ဆက်တင်များကိုသတ်မှတ်ပါ',
        port: 'Proxy Port',
        port_desc: 'အက်ပလီကေးရှင်း proxy port ကိုသတ်မှတ်ပါ',
        share_vpn: 'ဖမ်းဆုပ်သောလိပ်စာ',
        share_vpn_desc: 'ကွန်ယက်တွင် proxy ကိုမျှဝေပါ',
        dns: 'DNS',
        dns_desc: 'ကြော်ငြာများနှင့် ပြင်းပြသောအကြောင်းအရာများကို ပိတ်လိုက်ပါ',
        dns_error: 'ဒါဟာ Warp နှင့် Gool နည်းလမ်းများတွင် အသုံးပြုနိုင်သည်',
        ip_data: 'IP စစ်ဆေးမှု',
        ip_data_desc: 'ချိတ်ဆက်ပြီးနောက် IP နှင့် တည်နေရာကိုပြပါ',
        data_usage: 'ဒေတာအသုံးပြုမှု',
        data_usage_desc: 'ဒေတာအသုံးပြုမှုနှင့် အချိန်မှတ်တမ်းအရှိန်ကိုပြပါ',
        dark_mode: 'အမှောင်မိုဒ်',
        dark_mode_desc: 'အက်ပလီကေးရှင်းပြသမှုမိုဒ်ကိုသတ်မှတ်ပါ',
        lang: 'ဘာသာစကား',
        lang_desc: 'အက်ပလီကေးရှင်းကိုဘာသာစကားပြောင်းလဲပါ',
        open_login: 'အခေါ်စတင်ချိန်တွင်ဖွင့်ပါ',
        open_login_desc: 'စနစ်စတင်ခြင်းအခါတွင်ဖွင့်ပါ',
        auto_connect: 'အလိုအလျောက်ချိတ်ဆက်မှု',
        auto_connect_desc: 'အက်ပလီကေးရှင်းဖွင့်သည့်အခါချိတ်ဆက်ပါ',
        start_minimized: 'စတင်ရာမှာမင်းနိုက်တက်',
        start_minimized_desc: 'အက်ပလီကေးရှင်းဖွင့်သည့်အခါ မင်းနိုက်တက်',
        system_tray: 'စနစ် tray',
        system_tray_desc: 'အစီအစဉ်ကို taskbar တွင်မထားပါ',
        force_close: 'ခါးသုတ်ပိတ်ရန်',
        force_close_desc: 'ထွက်ပါက system tray တွင်မထိုင်ပါ',
        shortcut: 'နောက်ပြန်ခလုတ်',
        shortcut_desc: 'ပင်မစာမျက်နှာတွင် shortcut များ',
        sound_effect: 'အသံအကျိုးသက်ရောက်မှု',
        sound_effect_desc: 'ချိတ်ဆက်မှုအောင်မြင်သောအခါအသံဖွင့်ပါသည်။',
        restore: 'ပြန်လည်ပြုပြင်ရန်',
        restore_desc: 'အကူအညီအခြေအနေကိုပြန်လည်သတ်မှတ်ပါ',
        scanner: 'စကင်နာဆက်တင်များ',
        scanner_alert:
            'သင့်အနေနှင့် အဆင့်သတ်မှတ်ထားသော endpoint အလိပ်လိပ်ကိုသုံးပါက စကင်နာကိုဖွင့်ပါ။',
        scanner_ip_type: 'အဆုံးသတ် IP အမျိုးအစား',
        scanner_ip_type_auto: 'အလိုအလျောက်',
        scanner_ip_type_desc: 'Endpoint IP ကိုရှာဖွေရန်',
        scanner_rtt: 'အချိန်အတော်ကြာ',
        scanner_rtt_default: 'အဓိက',
        scanner_rtt_desc: 'စကင်နာ RTT ကန့်သတ်ချက်',
        scanner_reserved: 'ကြောင့်မပယ်',
        scanner_reserved_desc:
            'wireguard က reserved အတွက်မျှော်မှန်းထားသောတန်ဖိုးကို override လုပ်ပါ',
        routing_rules: 'Blacklist',
        routing_rules_desc: 'Traffic ကို warp မှတဆင့်မသွားအောင်အကာအရံထားပါ',
        routing_rules_disabled: 'ပိတ်ထားသည်',
        routing_rules_items: 'ပစ္စည်းများ',
        profile: 'ပရိုဖိုင်',
        profile_desc: 'သင်၏ saved endpoint များ',
        singbox: 'Tunnel ကွက်ရင်း',
        close_singbox: 'စနစ်တက်သည့်အခါတင်မဟုတ်ပါ',
        close_singbox_desc: 'Sing-box ကိုဆက်တင်ရင်လိုအပ်ချက်များကိုပိတ်ပါ',
        close_helper: 'ဂုဏ်မခံကောင်းပြန်ရေး',
        close_helper_desc: 'Exitခဲ့ခြင်းနေရာကိုပိတ်ဆို့ထားပါ',
        mtu: 'MTU တန်ဖိုး',
        mtu_desc: 'အများဆုံးပြောင်းလဲမှုအယူခံတန်ဖိုးကိုသတ်မှတ်ပါ',
        geo_block: 'ပိတ်ဆို့ခြင်း',
        geo_block_desc: 'ကြော်ငြာများ၊ Malware၊ Phishing နှင့် Crypto Miners',
        geo_rules_ip: 'IP Routing',
        geo_rules_ip_desc: 'GeoIP စည်းမျဉ်းများကိုလျှောက်ထားပါ',
        geo_rules_site: 'Web Routing',
        geo_rules_site_desc: 'GeoSite စည်းမျဉ်းများကိုလျှောက်ထားပါ',
        geo_nsfw_block: 'အကြောင်းအရာ ဖILTER',
        geo_nsfw_block_desc: 'NSFW ဝဘ်ဆိုဒ်များကို ပိတ်ဆို့မည်',
        more_helper: 'အကူအညီဆက်တင်များ',
        singbox_log: 'Logging',
        singbox_log_desc: 'Log အဆင့်ကိုသတ်မှတ်ပါ',
        singbox_stack: 'Stack',
        singbox_stack_desc: 'Stack အမျိုးအစားကိုသတ်မှတ်ပါ',
        singbox_sniff: 'Sniff',
        singbox_sniff_desc: 'Sniffing ကိုဖွင့်ပြီး ရောက်ရှိမှုကို Override လုပ်ပါ',
        singbox_addressing: 'လိပ်စာတင်ခြင်း',
        singbox_addressing_desc: 'Interface လိပ်စာအမျိုးအစားသတ်မှတ်ပါ',
        singbox_udp_block: 'UDP ကိုပိတ်မည်',
        singbox_udp_block_desc: 'UDP traffic အားလုံးကိုလုံးဝပိတ်မည်',
        singbox_discord_bypass: 'Discord',
        singbox_discord_bypass_desc: 'Discord ဖျက်တားမှုကိုကျော်လွှားခြင်း',
        more_duties: 'ပိုမိုတာဝန်များ',
        beta_release: 'ဘီတာအပ်ဒိတ်',
        beta_release_desc: 'မပြန်ပေးမီဗားရှင်းများကိုအသိပေးချက်ရယူပါ'
    },
    tabs: {
        home: 'ချိတ်ဆက်ပါ',
        warp: 'Warp',
        network: 'အင်တာနက်',
        scanner: 'စကင်နာ',
        app: 'အက်ပ်',
        singbox: 'တန်နယ်'
    },
    modal: {
        endpoint_title: 'Endpoint',
        license_title: 'လိုင်စင်',
        license_desc:
            'ဒီပရိုဂရမ်ကို လည်ပတ်ရန် Warp license တစ်ခု မလိုအပ်ပါဘူး၊ သို့သော် သင်သည် ဆန္ဒရှိလျှင်၊ ဤနေရာတွင် လိုင်စင်ကို ထည့်နိုင်ပါသည်။',
        form_clear: 'ရှင်းလင်းပါ',
        test_url_title: 'စမ်းသပ် URL',
        test_url_desc: 'ချိတ်ဆက်မှု စမ်းသပ်ရန်လိပ်စာ',
        test_url_update: 'အကြံပြုချက်များလက်ခံခြင်း',
        port_title: 'Proxy Port',
        restore_title: 'ပြန်လည်ဆက်သွယ်မှု',
        restore_desc:
            'ပြန်လည်ဆက်သွယ်မှု ပြုလုပ်ခြင်းဖြင့် ပရိုဂရမ်၏ စည်းမျဉ်းများသည် အခြားမှတ်တမ်းများမှပြန်လည်သတ်မှတ်ပြီး connection ကို ခွဲထွက်ပါသည်။',
        routing_rules_sample: 'နမူနာ',
        routing_rules_alert_tun:
            'Domain, IP နှင့် App အတွက်သာ Routing စည်းမျဉ်းများသည် Tun configuration ကို အကျိုးသက်ရောက်ပါမည်။',
        routing_rules_alert_system:
            'App Routing စည်းမျဉ်းမှ အပြောင်းအလဲသည် အခြား rules များကို ဆက်သွယ်မှု Proxy configuration တွင် တည်ရှိပါမည်။',
        form_default: 'ပုံမှန်',
        endpoint_suggested: 'အကြံပြု',
        endpoint_latest: 'နောက်ဆုံး',
        endpoint_update: 'Suggested Endpoints လက်ခံပါ',
        endpoint_paste: 'Paste Active Endpoint',
        profile_title: 'Profile',
        profile_name: 'အမည်',
        profile_endpoint: 'Endpoint',
        profile_limitation: (value) => `သင်သည် ${value} endpoints အထိ ပေါင်းထည့်နိုင်ပါသည်။`,
        mtu_title: 'MTU တန်ဖိုး',
        mtu_desc:
            'Maximum Transmission Unit (MTU) သည် ဒေတာပုံသေ၏ အရွယ်အစားကို သတ်မှတ်သည်။ 1000 မှ 9999 အတွင်းတွင် သတ်မှတ်ပါ။',
        custom_dns_title: 'စိတ်ကြိုက် DNS',
        confirm: 'ကန့်သတ်ပါ',
        update: 'အပ်ဒိတ်',
        cancel: 'အနှိပ်ပါ',
        yes: 'ဟုတ်ပါတယ်',
        no: 'မဟုတ်ပါ'
    },
    log: {
        title: 'အက်ပ်မှတ်တမ်း',
        desc: 'အမှားတစ်ခု ဖြစ်လာသောအခါ မှတ်တမ်းများကို ဒီနေရာတွင် ပြသပါမည်။',
        error_invalid_license: 'ထည့်ထားသော license မဟုတ်ပါ; ဖျက်ပစ်ပါ။',
        error_too_many_connected: 'License သုံးစွဲအကန့်အသတ် ပြည့်ခဲ့ပါသည်; ဖျက်ပစ်ပါ။',
        error_access_denied: 'ပရိုဂရမ်ကို Administrator အဖြစ် Run ပြုလုပ်ပါ။',
        error_failed_set_endpoint: 'Endpoint မတတ်နိုင်ပါ။ Endpoint ရွေးလဲပါ။',
        error_warp_identity: 'Cloudflare တွင် အတည်ပြုမှုအမှား ဖြစ်ပွားခဲ့သည်။',
        error_script_failed: 'ပရိုဂရမ်မှ အမှားဖြစ်ပွားနေပါသည်။ ထပ်၍ ကြိုးစားပါ။',
        error_object_null: 'ပရိုဂရမ်မှ အမှားဖြစ်ပွားနေပါသည်။ ထပ်၍ ကြိုးစားပါ။',
        error_port_already_in_use: (value) =>
            `${value} port အတည်ပြုရန် အသုံးပြုနေပါသည်။ အခြား port ပြောင်းလဲပါ။`,
        error_port_socket: 'Port ကို အသုံးပြုရန် အခြား port အသုံးပြုပါ။',
        error_port_restart: 'Port ကို အသုံးပြုနေသည်။ ပြန်လည်စတင်ပါ ...',
        error_unknown_flag: 'အမှားကို command ထည့်ခဲ့ပါသည်။',
        error_deadline_exceeded: 'ချိတ်ဆက်ရန် အချိန်ကုန်သွားပြီ။ ထပ်၍ ကြိုးစားပါ။',
        error_configuration_encountered: 'Proxy configuration မှာ အမှားရှိနေပါသည်။',
        error_desktop_not_supported: 'Desktop ပတ်ဝန်းကျင် ကို ပံ့ပိုးမထားပါ။',
        error_configuration_not_supported:
            'Proxy configuration သည် သင့်စက်ပေါ်တွင် မပံ့ပိုးနိုင်ပါ။ သို့သော် Warp Proxy ကို ကိုယ်တိုင်အသုံးပြုနိုင်သည်။',
        error_configuring_proxy: (value) => `${value} proxy အတွက် ပြဿနာ ဖြစ်ခဲ့ပါသည်။`,
        error_wp_not_found: 'warp-plus ဖိုင်သည် ပရိုဂရမ်အဖွဲ့နှင့်အတူ တည်ရှိမည်မဟုတ်ပါ။',
        error_mp_not_found: 'masque-plus ဖိုင်ကို အက်ပ်ပလီကေးရှင်းထုပ်ပိုးမှုနှင့်အတူ မတွေ့ရှိပါ!',
        error_usque_not_found: 'usque ဖိုင်ကို အက်ပ်ပလီကေးရှင်းထုပ်ပိုးမှုနှင့်အတူ မတွေ့ရှိပါ!',
        error_wp_exclusions:
            'ကြားဖြတ်မမှန်ခြင်းနှင့်အန်တီဗိုင်းရပ်စ်မှမှားသောရှာဖွေမှုကြောင့် warp-plus ဖိုင်ကိုကာကွယ်ထားခဲ့ပြီး အစီအစဉ်၏အင်တာနက်မှ အခွင့်အလမ်းရရှိခြင်းတွင်ပြproblemများဖြစ်စေပါသည်။\nအစီအစဉ်သည် အချို့သောအန်တီဗိုင်းရပ်စ်များတွင် ဖိုင်ကို ပယ်ပွဲကောက်စာရင်းသို့ထည့်နိုင်သည်။ ၎င်းကို လုပ်ဆောင်သင့်ပါသလား?',
        error_wp_stopped: 'warp-plus ဖိုင်တွင် ပြဿနာရှိနေပါသည်။',
        error_connection_failed: '1.1.1.1 နှင့် ချိတ်ဆက်၍ မရနိုင်ပါ။',
        error_country_failed: 'ရွေးချယ်ထားသောနိုင်ငံနှင့် ချိတ်ဆက်၍ မရနိုင်ပါ။',
        error_singbox_failed_stop: 'Sing-Box ပိတ်ထားရန် မအောင်မြင်ပါ။',
        error_singbox_failed_start: 'Sing-Box စတင်ရန် မအောင်မြင်ပါ။',
        error_wp_reset_peer: 'Cloudflare နှင့် ချိတ်ဆက်မှု ပျက်သွားသည်!',
        error_failed_connection: 'ချိတ်ဆက်မှုကို တည်ဆောက်၍ မရနိုင်ပါ။',
        error_canceled_by_user: 'အသုံးပြုသူမှ အလုပ်လုပ်ကိုင်မှုကို မဆိုင်းငံ့သွားပါ။',
        error_helper_not_found: 'အကူအညီဖိုင်ကို အပလီကေးရှင်းပက်ကေ့တစ်ခုနှင့်အတူ တွေ့ရှိမရပါ!',
        error_singbox_ipv6_address:
            'သင်၏အပလီကေးရှင်းစနစ်သည် IPv6 ကို မပံ့ပိုးပါ။ ကျေးဇူးပြုပြီး တန်နယ်ဆက်တင်များသို့သွားပြီး လိပ်စာကို IPv4 သို့ပြောင်းပါ။',
        error_local_date:
            'သင့်စနစ်၏ ရက်စွဲနှင့် အချိန်ကို မှန်ကန်စွာ သတ်မှတ်ထားခြင်းဖြစ်ကြောင်း သေချာပါစေ။'
    },
    about: {
        title: 'အက်ပ်အကြောင်း',
        desc: 'ဒီပရိုဂရမ်သည် Windows, Linux, Mac တို့အတွက် Oblivion app ၏ တရားမဝင်သော်လည်း ယုံကြည်မှုရှိသော ဗားရှင်းဖြစ်သည်။\nOblivion Desktop ပရိုဂရမ်သည် Yousef Ghobadi ၏ ဦးစွာဖွံ့ဖြိုးပွားသော interface မှထုတ်လုပ်ထားပြီး free access to the internet purpose အတွက်ရေးသားပြီး ငွေတောင်းသော်လည်းအမည်ပြောင်းလဲမှု နှင့် စီးပွားရေး အသုံးပြုခြင်းကို ခွင့်မပြုပါ။',
        slogan: 'အင်တာနက်သည် မည်သည့်လူတစ်ယောက်အတွက်မဆို ရရှိနိုင်သည်!'
    },
    systemTray: {
        connect: 'ချိတ်ဆက်ပါ',
        connecting: 'ချိတ်ဆက်နေသည် ...',
        connected: 'ချိတ်ဆက်ပြီးပြီ',
        disconnecting: 'ခွဲထွက်နေသည် ...',
        settings: 'ဆက်တင်များ',
        settings_warp: 'Warp',
        settings_network: 'ကွန်ယက်',
        settings_scanner: 'စကင်နာ',
        settings_app: 'အက်ပလီကေးရှင်း',
        about: 'အကြောင်း',
        log: 'မှတ်တမ်း',
        speed_test: 'အရှိန် စမ်းသပ်မှု',
        exit: 'ထွက်ရန်'
    },
    update: {
        available: 'အပ်ဒိတ် ရနိုင်သည်',
        available_message: (value) =>
            `${value} ၏ အသစ်ဗားရှင်း တင်ထားရှိပါသည်။ ယခု အပ်ဒိတ်လုပ်လိုပါသလား?`,
        ready: 'အပ်ဒိတ် ရပြီးပြီ',
        ready_message: (value) =>
            `${value} ၏ အသစ်ဗားရှင်း ရပြီးပြီ။ ပြန်လည်စတင်ပြီးနောက်တွင် တင်ဆက်မည်။ ယခု စတင်လိုပါသလား?`
    },
    speedTest: {
        title: 'အမြန်နှုန်း စမ်းသပ်မှု',
        initializing: 'အမြန်နှုန်း စမ်းသပ်မှု စတင်နေသည် ...',
        click_start: 'အမြန်နှုန်း စမ်းသပ်မှု စတင်ရန် ခလုတ်ကိုနှိပ်ပါ',
        error_msg: 'အမြန်နှုန်း စမ်းသပ်မှုတွင်အမှားတစ်ခု ဖြစ်ပွားခဲ့ပါသည်။ ထပ်မံကြိုးစားပါ။',
        server_unavailable: 'အမြန်နှုန်း စမ်းသပ်မှုဆာဗာ မရရှိနိုင်ပါ',
        download_speed: 'ဒေါင်းလိုက် အမြန်နှုန်း',
        upload_speed: 'တင်လိုက် အမြန်နှုန်း',
        latency: 'လက်ရှိနှောင့်နှေးမှု',
        jitter: 'Jitter'
    }
};
export default myanmar;
