import { Language } from './type';

const dutch: Language = {
    global: {},
    status: {
        connecting: 'Verbinden...',
        connected: 'Verbonden',
        connected_confirm: 'Verbonden',
        disconnecting: 'Verbinding verbreken...',
        disconnected: 'Verbinding verbroken',
        ip_check: 'IP controleren...',
        keep_trying: 'Even wachten om opnieuw te proberen...',
        preparing_rulesets: 'Rulesets voorbereiden...',
        downloading_rulesets_failed: 'Downloaden van rulesets mislukt.'
    },
    home: {
        title_warp_based: 'Warp Gebaseerd',
        drawer_settings_warp: 'Warp Instellingen',
        drawer_settings_routing_rules: 'Routing Regels',
        drawer_settings_app: 'App Instellingen',
        drawer_settings_scanner: 'Scanner Instellingen',
        drawer_settings_network: 'Netwerk Instellingen',
        drawer_log: 'App Logboek',
        drawer_update: 'Update',
        drawer_update_label: 'Nieuwe Update',
        drawer_speed_test: 'Snelheidstest',
        drawer_about: 'Over de App',
        drawer_lang: 'Taal wijzigen',
        drawer_singbox: 'Tunnel Instellingen'
    },
    toast: {
        ip_check_please_wait: 'Wacht een paar seconden voordat je het opnieuw probeert!',
        ir_location:
            'Cloudflare is verbonden met een Iraans IP (anders dan je echte IP). Dit kan filtering omzeilen maar geen sancties. Je kunt locaties wijzigen via "Gool" of "Psiphon" in de instellingen.',
        btn_submit: 'Begrepen',
        copied: 'Gekopieerd!',
        cleared: 'Het logboek is geleegd!',
        please_wait: 'Even geduld...',
        offline: 'Je bent offline!',
        settings_changed: 'Toepassen van instellingen vereist opnieuw verbinden.',
        hardware_usage: 'Deze optie verhoogt het gebruik van hardwarebronnen.',
        config_added:
            'Configuratie succesvol toegevoegd. Klik op verbinden om het te gebruiken.',
        profile_added: 'Endpoint succesvol toegevoegd aan profiel.',
        endpoint_added: 'Endpoint succesvol vervangen.',
        new_update: 'Er is een nieuwe versie van de app beschikbaar. Wil je deze downloaden en voorbereiden voor installatie?',
        exit_pending: 'De app is nog bezig met afsluiten; wacht even voordat je opnieuw start.',
        help_btn: 'Hulp'
    },
    settings: {
        title: 'Warp Instellingen',
        more: 'Meer Instellingen',
        method_warp: 'Warp',
        method_warp_desc: 'Warp inschakelen',
        method_gool: 'Gool',
        method_gool_desc: 'WarpInWarp inschakelen',
        method_psiphon: 'Psiphon',
        method_psiphon_desc: 'Psiphon inschakelen',
        method_psiphon_location: 'Land',
        method_psiphon_location_auto: 'Willekeurig',
        method_psiphon_location_desc: 'Kies gewenst land-IP',
        endpoint: 'Endpoint',
        endpoint_desc: 'Combinatie van IP of domein met poort',
        license: 'Licentie',
        license_desc: 'Het verbruik van de licentie wordt verdubbeld',
        option: 'Applicatie-instellingen',
        network: 'Netwerkinstellingen',
        proxy_mode: 'Configuratie',
        proxy_mode_desc: 'Proxy-instellingen definiëren',
        port: 'Proxy Poort',
        port_desc: 'Lokale proxy luisterpoort instellen',
        share_vpn: 'Bind Adres',
        share_vpn_desc: 'Proxy delen op netwerk',
        dns: 'DNS',
        dns_desc: 'Blokkeer advertenties en volwassen inhoud',
        dns_error: 'Geldig voor Warp & Gool methodes',
        ip_data: 'IP Controle',
        ip_data_desc: 'IP & locatie tonen na verbinding',
        data_usage: 'Dataverbruik',
        data_usage_desc: 'Toon dataverbruik & real-time snelheid',
        dark_mode: 'Donkere Modus',
        dark_mode_desc: 'Weergavemodus van de app instellen',
        lang: 'Taal',
        lang_desc: 'Interface-taal wijzigen',
        open_login: 'Start bij inloggen',
        open_login_desc: 'Open bij systeemstart',
        auto_connect: 'Automatisch Verbinden',
        auto_connect_desc: 'Verbind bij het openen van de app',
        start_minimized: 'Geminimaliseerd Starten',
        start_minimized_desc: 'Minimaliseer bij openen',
        system_tray: 'Systeemvak',
        system_tray_desc: 'Geen pictogram in taakbalk plaatsen',
        force_close: 'Geforceerd Afsluiten',
        force_close_desc: 'Niet actief blijven in systeemvak',
        shortcut: 'Snelkoppeling',
        shortcut_desc: 'Snelkoppelingen op de startpagina',
        sound_effect: 'Geluideffect',
        sound_effect_desc: 'Geluid afspelen bij succesvolle verbinding',
        restore: 'Herstellen',
        restore_desc: 'Standaardinstellingen toepassen',
        scanner: 'Scanner Instellingen',
        scanner_alert: 'Scanner is actief bij standaard endpoint-adres.',
        scanner_ip_type: 'Endpoint Type',
        scanner_ip_type_auto: 'Automatisch',
        scanner_ip_type_desc: 'Voor vinden van endpoint IP',
        scanner_rtt: 'Interval',
        scanner_rtt_default: 'Standaard',
        scanner_rtt_desc: 'RTT-limiet scanner',
        scanner_reserved: 'Gereserveerd',
        scanner_reserved_desc: 'Waarde overschrijven voor wireguard',
        routing_rules: 'Zwarte Lijst',
        routing_rules_desc: 'Verkeer via Warp voorkomen',
        routing_rules_disabled: 'Uitgeschakeld',
        routing_rules_items: 'Items',
        profile: 'Profiel',
        profile_desc: 'Door jou opgeslagen endpoints',
        singbox: 'Tunnel Instellingen',
        close_singbox: 'Stop operatie',
        close_singbox_desc: 'Sing-Box automatisch stoppen bij verbreken',
        close_helper: 'Stop helper',
        close_helper_desc: 'Helper automatisch stoppen bij afsluiten',
        mtu: 'MTU Waarde',
        mtu_desc: 'Maximale transmissie-eenheid instellen',
        geo_block: 'Blokkering',
        geo_block_desc: 'Advertenties, malware, phishing & cryptominers',
        geo_rules_ip: 'IP Routing',
        geo_rules_ip_desc: 'GeoIP regels toepassen',
        geo_rules_site: 'Web Routing',
        geo_rules_site_desc: 'GeoSite regels toepassen',
        geo_nsfw_block: 'Inhoudsfilter',
        geo_nsfw_block_desc: 'Blokkeer NSFW-websites',
        more_helper: 'Assistent Instellingen',
        singbox_log: 'Logboek',
        singbox_log_desc: 'Logniveau instellen',
        singbox_stack: 'Stack',
        singbox_stack_desc: 'Stacktype instellen',
        singbox_sniff: 'Sniff',
        singbox_sniff_desc: 'Sniffing inschakelen & bestemming overschrijven',
        singbox_addressing: 'Adressering',
        singbox_addressing_desc: 'Interface-adrestype instellen',
        singbox_udp_block: 'Blokkeer UDP',
        singbox_udp_block_desc: 'Alle UDP-verkeer volledig blokkeren',
        singbox_discord_bypass: 'Discord',
        singbox_discord_bypass_desc: 'Discord-filtering omzeilen',
        more_duties: 'Taken',
        beta_release: 'Beta Update',
        beta_release_desc: 'Blijf op de hoogte van pre-releases'
    },
    tabs: {
        home: 'Verbinding',
        warp: 'Warp',
        network: 'Netwerk',
        scanner: 'Scanner',
        app: 'App',
        singbox: 'Tunnel'
    },
    modal: {
        endpoint_title: 'Endpoint',
        license_title: 'Licentie',
        license_desc: 'De app heeft niet per se een Warp-licentie nodig, maar je kunt er hier een invoeren.',
        form_clear: 'Wissen',
        test_url_title: 'Test URL',
        test_url_desc: 'Adres voor verbindingscontrole',
        test_url_update: 'Suggesties ontvangen',
        port_title: 'Proxy Poort',
        restore_title: 'Herstel Wijzigingen',
        restore_desc: 'Alle instellingen worden teruggezet en je verbinding wordt verbroken.',
        routing_rules_sample: 'Voorbeeld',
        routing_rules_alert_tun: 'Alleen regels voor domein, IP & app beïnvloeden de Tun-configuratie.',
        routing_rules_alert_system: 'Behalve de app-regel beïnvloeden andere regels de systeemproxy.',
        form_default: 'Standaard',
        endpoint_suggested: 'Voorgesteld',
        endpoint_latest: 'Laatste',
        endpoint_update: 'Voorgestelde endpoints ophalen',
        endpoint_paste: 'Actieve endpoint plakken',
        profile_title: 'Profiel',
        profile_name: 'Naam',
        profile_endpoint: 'Endpoint',
        profile_limitation: (value) => `Maximaal ${value} endpoints toegestaan.`,
        mtu_title: 'MTU Waarde',
        mtu_desc: 'De maximale pakketgrootte moet tussen 1000 en 9999 liggen.',
        custom_dns_title: 'Aangepaste DNS',
        confirm: 'Ik bevestig',
        update: 'Bijwerken',
        cancel: 'Annuleren'
    },
    log: {
        title: 'App Logboek',
        desc: 'Logbestanden worden hier weergegeven indien aanwezig.',
        error_invalid_license: 'De ingevoerde licentie is ongeldig. Verwijder deze.',
        error_too_many_connected: 'Licentielimiet bereikt. Verwijder deze.',
        error_access_denied: 'Start de app als Administrator.',
        error_failed_set_endpoint: 'Controleer of wijzig het endpoint, of probeer opnieuw.',
        error_warp_identity: 'Cloudflare-authenticatiefout!',
        error_script_failed: 'Er is een fout opgetreden. Probeer opnieuw.',
        error_object_null: 'Er is een fout opgetreden. Probeer opnieuw.',
        error_port_already_in_use: (value) =>
            `Poort ${value} wordt al gebruikt. Kies een andere.`,
        error_port_socket: 'Gebruik een andere poort.',
        error_port_restart: 'Poort in gebruik; opnieuw starten ...',
        error_unknown_flag: 'Ongeldig commando op de achtergrond uitgevoerd.',
        error_deadline_exceeded: 'Tijdslimiet verbinding overschreden. Probeer opnieuw.',
        error_configuration_encountered: 'Fout in proxyconfiguratie!',
        error_desktop_not_supported: 'Desktopomgeving wordt niet ondersteund!',
        error_configuration_not_supported:
            'Proxyconfiguratie wordt niet ondersteund in je OS. Gebruik Warp Proxy handmatig.',
        error_configuring_proxy: (value) => `Fout bij instellen van proxy voor ${value}!`,
        error_wp_not_found: 'warp-plus-bestand ontbreekt naast de app!',
        error_wp_exclusions:
            'Het warp-plus-bestand is waarschijnlijk door antivirus in quarantaine geplaatst. Wil je het toevoegen aan de uitsluitingen?',
        error_wp_stopped: 'warp-plus-bestand kon niet worden uitgevoerd!',
        error_connection_failed: 'Verbinding met 1.1.1.1 mislukt.',
        error_country_failed: 'Kan geen verbinding maken met geselecteerd land.',
        error_singbox_failed_stop: 'Stoppen van Sing-Box mislukt!',
        error_singbox_failed_start: 'Starten van Sing-Box mislukt!',
        error_wp_reset_peer: 'Verbinding met Cloudflare onverwacht verbroken!',
        error_failed_connection: 'Verbinding kon niet worden gemaakt!',
        error_canceled_by_user: 'Actie geannuleerd door gebruiker.',
        error_helper_not_found: 'helper-bestand ontbreekt naast de app!',
        error_singbox_ipv6_address:
            'Je OS ondersteunt geen IPv6. Wijzig de adressering naar IPv4 in de tunnelinstellingen.',
        error_local_date: 'Zorg ervoor dat datum en tijd van je systeem correct zijn ingesteld!'
    },
    about: {
        title: 'Over de App',
        desc: 'Dit is een niet-officiële maar betrouwbare desktopversie van Oblivion voor Windows, Linux en macOS.\nGebaseerd op de originele interface van Yousef Ghobadi. Naamwijziging of commercieel gebruik is verboden.',
        slogan: 'Internet, voor iedereen of niemand!'
    },
    systemTray: {
        connect: 'Verbinden',
        connecting: 'Verbinden ...',
        connected: 'Verbonden',
        disconnecting: 'Verbinding verbreken ...',
        settings: 'Instellingen',
        settings_warp: 'Warp',
        settings_network: 'Netwerk',
        settings_scanner: 'Scanner',
        settings_app: 'Applicatie',
        about: 'Over',
        log: 'Logboeken',
        speed_test: 'Snelheidstest',
        exit: 'Afsluiten'
    },
    update: {
        available: 'Update Beschikbaar',
        available_message: (value) => `Nieuwe versie ${value} beschikbaar. Nu bijwerken?`,
        ready: 'Update Klaar',
        ready_message: (value) => `Update ${value} voorbereid. Nu herstarten om te installeren?`
    },
    speedTest: {
        title: 'Snelheidstest',
        initializing: 'Snelheidstest initialiseren ...',
        click_start: 'Klik om te beginnen',
        error_msg: 'Snelheidstest mislukt. Probeer opnieuw.',
        server_unavailable: 'Snelheidstestserver niet beschikbaar',
        download_speed: 'Downloadsnelheid',
        upload_speed: 'Uploadsnelheid',
        latency: 'Latentie',
        jitter: 'Jitter'
    }
};

export default dutch;
