import { Language } from './type';

const urdu: Language = {
    global: {},
    status: {
        connecting: 'کنیکٹ ہو رہا ہے...',
        connected: 'کنیکٹڈ',
        connected_confirm: 'کنیکٹڈ کی تصدیق ہو گئی',
        disconnecting: 'ڈسکنیکٹ ہو رہا ہے...',
        disconnected: 'ڈسکنیکٹڈ',
        ip_check: 'آئی پی چیک ہو رہا ہے...',
        keep_trying: 'براہ کرم دوبارہ کوشش کے لیے چند لمحے انتظار کریں...',
        preparing_rulesets: 'قواعد کا سیٹ تیار کیا جا رہا ہے...',
        downloading_rulesets_failed: 'قواعد کا سیٹ ڈاؤن لوڈ کرنے میں ناکام.'
    },
    home: {
        title_warp_based: 'وارپ بیسڈ',
        drawer_settings_warp: 'وارپ سیٹنگز',
        drawer_settings_routing_rules: 'روٹنگ رولز',
        drawer_settings_app: 'ایپ سیٹنگز',
        drawer_settings_scanner: 'سکینر سیٹنگز',
        drawer_settings_network: 'نیٹ ورک سیٹنگز',
        drawer_log: 'ایپ لاگ',
        drawer_update: 'اپڈیٹ',
        drawer_update_label: 'نئی اپڈیٹ دستیاب ہے',
        drawer_speed_test: 'اسپیڈ ٹیسٹ',
        drawer_about: 'ایپ کے بارے میں',
        drawer_lang: 'زبان تبدیل کریں',
        drawer_singbox: 'ٹنل کی ترتیبات'
    },
    toast: {
        ip_check_please_wait: 'براہ کرم چند سیکنڈ انتظار کریں اور دوبارہ چیک کریں!',
        ir_location:
            'کلاؤڈ فلئیر نے ایرانی لوکیشن کے آئی پی سے کنیکٹ کیا ہے، جو آپ کے اصلی آئی پی سے مختلف ہے۔ آپ اسے فلٹرنگ بائی پاس کے لیے استعمال کر سکتے ہیں، لیکن پابندیوں کے لیے نہیں۔ پریشان نہ ہوں! آپ اسے سیٹنگز میں "گول" یا "سائفون" آپشن کا استعمال کر کے تبدیل کر سکتے ہیں۔',
        btn_submit: 'سمجھ گیا',
        copied: 'کاپی ہو گیا!',
        cleared: 'لاگ صاف کر دیا گیا!',
        please_wait: 'براہ کرم انتظار کریں...',
        offline: 'آپ آف لائن ہیں!',
        settings_changed: 'سیٹنگز کو نافذ کرنے کے لیے دوبارہ کنیکٹ ہونا ضروری ہے۔',
        hardware_usage: 'اس آپشن کو فعال کرنے سے ہارڈویئر وسائل کے استعمال میں اضافہ ہوگا۔',
        config_added:
            'کنفیگریشن کامیابی سے شامل کر دی گئی ہے، اور اسے استعمال کرنے کے لیے آپ کو کنکشن پر کلک کرنا ہوگا۔',
        profile_added: 'اینڈپوائنٹ کامیابی سے پروفائل میں شامل کیا گیا۔',
        endpoint_added: 'اینڈ پوائنٹ کو کامیابی کے ساتھ تبدیل کر دیا گیا۔',
        new_update_notification: 'نیا ورژن دستیاب ہے',
        new_update:
            'ایپ کا نیا ورژن دستیاب ہے۔ کیا آپ اسے ڈاؤن لوڈ کرکے انسٹالیشن کے لیے تیار کرنا چاہیں گے؟',
        up_to_date: 'آپ ایپ کا تازہ ترین ورژن استعمال کر رہے ہیں',
        exit_pending:
            'ایپلیکیشن اپنے بند ہونے کے عمل کو مکمل کر رہی ہے؛ دوبارہ لانچ کرنے سے پہلے کچھ لمحے انتظار کریں۔',
        help_btn: 'مدد'
    },
    settings: {
        title: 'وارپ کی ترتیبات',
        more: 'مزید ترتیبات',
        method_warp: 'وارپ',
        method_warp_desc: 'وارپ فعال کریں',
        method_gool: 'گول',
        method_gool_desc: 'وارپ ان وارپ فعال کریں',
        method_masque: 'ماسک',
        method_masque_desc: 'ماسک فعال کریں',
        method_psiphon: 'سائفون',
        method_psiphon_desc: 'سائفون فعال کریں',
        method_psiphon_location: 'ملک',
        method_psiphon_location_auto: 'بے ترتیب',
        method_psiphon_location_desc: 'پسندیدہ ملک کا آئی پی منتخب کریں',
        endpoint: 'اینڈپوائنٹ',
        endpoint_desc: 'آئی پی یا ڈومین نام کا مجموعہ، پورٹ کے ساتھ',
        license: 'لائسنس',
        license_desc: 'لائسنس کا استعمال دگنا ہو جاتا ہے',
        option: 'ایپلیکیشن ترتیبات',
        network: 'نیٹ ورک ترتیبات',
        proxy_mode: 'کنفیگریشن',
        proxy_mode_desc: 'پراکسی ترتیبات کی وضاحت کریں',
        port: 'پراکسی پورٹ',
        port_desc: 'ایپلیکیشن پراکسی پورٹ متعین کریں',
        share_vpn: 'بندش کا پتہ',
        share_vpn_desc: 'نیٹ ورک پر پراکسی شیئر کریں',
        dns: 'ڈی این ایس',
        dns_desc: 'اشتہارات اور بالغ مواد کو بلاک کریں',
        dns_error: 'یہ وارپ اور گول طریقوں پر لاگو ہوتا ہے',
        ip_data: 'آئی پی چیک',
        ip_data_desc: 'کنیکشن کے بعد آئی پی اور مقام دکھائیں',
        data_usage: 'ڈیٹا استعمال',
        data_usage_desc: 'ڈیٹا استعمال اور حقیقی وقت کی رفتار دکھائیں',
        dark_mode: 'ڈارک موڈ',
        dark_mode_desc: 'ایپلیکیشن کا ڈسپلے موڈ منتخب کریں',
        lang: 'زبان',
        lang_desc: 'ایپلیکیشن انٹرفیس کی زبان تبدیل کریں',
        open_login: 'لاگ ان پر شروع کریں',
        open_login_desc: 'سسٹم اسٹارٹ اپ پر کھولیں',
        auto_connect: 'خودکار کنکشن',
        auto_connect_desc: 'ایپ کھلتے ہی کنکٹ کریں',
        start_minimized: 'شروع ہونے پر کم سے کم',
        start_minimized_desc: 'ایپلیکیشن کھلتے ہی کم کرنا',
        system_tray: 'سسٹم ٹرے',
        system_tray_desc: 'پروگرام آئیکون کو ٹاسک بار میں نہ رکھیں',
        force_close: 'زبردستی بند کریں',
        force_close_desc: 'ایگزٹ پر سسٹم ٹرے میں نہ رہیں',
        shortcut: 'نیویگیٹر',
        shortcut_desc: 'ہوم پیج پر شارٹ کٹس',
        sound_effect: 'آواز کا اثر',
        sound_effect_desc: 'کامیاب کنکشن پر آواز بجاتا ہے',
        restore: 'بحال کریں',
        restore_desc: 'ڈیفالٹ ایپلیکیشن ترتیبات لاگو کریں',
        scanner: 'سکینر کی ترتیبات',
        scanner_alert:
            'اگر آپ ڈیفالٹ اینڈپوائنٹ ایڈریس استعمال کر رہے ہیں تو سکینر فعال ہو جاتا ہے۔',
        scanner_ip_type: 'اینڈپوائنٹ قسم',
        scanner_ip_type_auto: 'خودکار',
        scanner_ip_type_desc: 'اینڈپوائنٹ آئی پی تلاش کرنے کے لیے',
        scanner_rtt: 'وقفہ',
        scanner_rtt_default: 'ڈیفالٹ',
        scanner_rtt_desc: 'سکینر RTT حد',
        scanner_reserved: 'ریزروڈ',
        scanner_reserved_desc: 'وائر گارڈ ریزروڈ ویلیو اوور رائڈ کریں',
        routing_rules: 'بلیک لسٹ',
        routing_rules_desc: 'ٹریفک کو وارپ سے گزرنے سے روکیں',
        routing_rules_disabled: 'غیر فعال',
        routing_rules_items: 'اشیاء',
        profile: 'پروفائل',
        profile_desc: 'آپ کے ذریعے محفوظ کیے گئے اینڈپوائنٹس',
        singbox: 'ٹنل کی ترتیبات',
        close_singbox: 'آپریشن بند کریں',
        close_singbox_desc: 'ڈسکنیکٹ پر خودکار طور پر سنگ باکس بند کریں',
        close_helper: 'مددگار بند کریں',
        close_helper_desc: 'ایگزٹ پر خودکار طور پر مددگار بند کریں',
        mtu: 'MTU ویلیو',
        mtu_desc: 'زیادہ سے زیادہ ٹرانسمیشن یونٹ مقرر کریں',
        geo_block: 'بلاکنگ',
        geo_block_desc: 'اشتہارات، میلویئر، فشنگ، اور کرپٹو مائنرز',
        geo_rules_ip: 'آئی پی روٹنگ',
        geo_rules_ip_desc: 'GeoIP قواعد لاگو کریں',
        geo_rules_site: 'ویب روٹنگ',
        geo_rules_site_desc: 'GeoSite قواعد لاگو کریں',
        geo_nsfw_block: 'مواد کی فلٹرنگ',
        geo_nsfw_block_desc: 'NSFW ویب سائٹس کو بلاک کریں',
        more_helper: 'مددگار کی ترتیبات',
        singbox_log: 'لاگنگ',
        singbox_log_desc: 'لاگ سطح سیٹ کریں',
        singbox_stack: 'اسٹیک',
        singbox_stack_desc: 'اسٹیک کی قسم سیٹ کریں',
        singbox_sniff: 'سنیفنگ',
        singbox_sniff_desc: 'سنیفنگ فعال کریں اور منزل کو اووررائیڈ کریں',
        singbox_addressing: 'ایڈریسنگ',
        singbox_addressing_desc: 'انٹرفیس ایڈریس کی قسم سیٹ کریں',
        singbox_udp_block: 'UDP بلاک کریں',
        singbox_udp_block_desc: 'UDP ٹریفک کو مکمل طور پر بلاک کریں',
        singbox_discord_bypass: 'ڈسکارڈ',
        singbox_discord_bypass_desc: 'ڈسکارڈ کی فلٹرنگ کو عبور کریں',
        more_duties: 'مزید ذمہ داریاں',
        beta_release: 'بیٹا اپ ڈیٹ',
        beta_release_desc: 'پری ریلیز ورژنز کے بارے میں آگاہ رہیں'
    },
    tabs: {
        home: 'کنیکٹ',
        warp: 'وارپ',
        network: 'نیٹ ورک',
        scanner: 'سکینر',
        app: 'ایپ',
        singbox: 'ٹنل'
    },
    modal: {
        endpoint_title: 'اینڈپوائنٹ',
        license_title: 'لائسنس',
        license_desc:
            'پروگرام کو چلانے کے لیے ضروری طور پر وارپ لائسنس کی ضرورت نہیں ہے، لیکن اگر آپ چاہیں تو اپنا لائسنس یہاں داخل کر سکتے ہیں۔',
        form_clear: 'صاف کریں',
        test_url_title: 'ٹیسٹ یو آر ایل',
        test_url_desc: 'کنیکٹوٹی ٹیسٹ ایڈریس',
        test_url_update: 'تجاویز موصول کریں',
        port_title: 'پراکسی پورٹ',
        restore_title: 'تبدیلیاں بحال کریں',
        restore_desc:
            'تبدیلیوں کو بحال کرنے کی تصدیق کرنے سے تمام پروگرام سیٹنگز ڈیفالٹ پر واپس آجائیں گی اور آپ کا کنیکشن منقطع ہو جائے گا۔',
        routing_rules_sample: 'نمونہ',
        routing_rules_alert_tun:
            'صرف ڈومین، آئی پی، اور ایپ کے لیے روٹنگ رولز "تن" کنفیگریشن کو متاثر کریں گے۔',
        routing_rules_alert_system:
            'ایپ روٹنگ رول کے علاوہ دیگر تمام رولز "سسٹم پراکسی" کنفیگریشن کو متاثر کریں گے۔',
        form_default: 'ڈیفالٹ',
        endpoint_suggested: 'تجویز کردہ',
        endpoint_latest: 'تازہ ترین',
        endpoint_update: 'تجویز کردہ اینڈپوائنٹ وصول کریں',
        endpoint_paste: 'فعال اینڈپوائنٹ چسپاں کریں',
        profile_title: 'پروفائل',
        profile_name: 'عنوان',
        profile_endpoint: 'اینڈپوائنٹ',
        profile_limitation: (value) => `آپ زیادہ سے زیادہ ${value} اینڈپوائنٹ شامل کر سکتے ہیں۔`,
        mtu_title: 'ایم ٹی یو ویلیو',
        mtu_desc:
            'زیادہ سے زیادہ ٹرانسمیشن یونٹ (MTU) ڈیٹا پیکٹ کے زیادہ سے زیادہ سائز کو ظاہر کرتا ہے، جسے 1000 اور 9999 کے درمیان مقرر کرنا چاہیے۔',
        custom_dns_title: 'حسب ضرورت DNS',
        confirm: 'میں تصدیق کرتا ہوں',
        update: 'اپڈیٹ',
        cancel: 'منسوخ کریں',
        yes: 'جی ہاں',
        no: 'نہیں'
    },
    log: {
        title: 'ایپ لاگ',
        desc: 'اگر پروگرام کی جانب سے کوئی لاگ تیار کیا گیا ہو، تو وہ یہاں دکھایا جائے گا۔',
        error_invalid_license: 'داخل کردہ لائسنس درست نہیں ہے؛ اسے ہٹا دیں۔',
        error_too_many_connected: 'لائسنس کا استعمال حد کو پہنچ چکا ہے؛ اسے ہٹا دیں۔',
        error_access_denied: 'پروگرام کو "ایڈمنسٹریٹر کے طور پر چلائیں"۔',
        error_failed_set_endpoint:
            'اینڈپوائنٹ ویلیو کو چیک کریں یا تبدیل کریں، یا دوبارہ کوشش کریں۔',
        error_warp_identity: 'کلاؤڈفلئیر میں توثیق کی غلطی!',
        error_script_failed: 'پروگرام کو ایک مسئلہ درپیش آیا؛ دوبارہ کوشش کریں۔',
        error_object_null: 'پروگرام کو ایک مسئلہ درپیش آیا؛ دوبارہ کوشش کریں۔',
        error_port_already_in_use: (value) =>
            `پورٹ ${value} کسی اور پروگرام کے ذریعے استعمال ہو رہی ہے؛ اسے تبدیل کریں۔`,
        error_port_socket: 'کوئی اور پورٹ استعمال کریں۔',
        error_port_restart: 'پورٹ استعمال میں ہے؛ دوبارہ شروع کیا جا رہا ہے ...',
        error_unknown_flag: 'بیک گراؤنڈ میں ایک غیر قانونی کمانڈ چلائی گئی۔',
        error_deadline_exceeded: 'کنیکشن کا وقت ختم ہو گیا؛ دوبارہ کوشش کریں۔',
        error_configuration_encountered: 'پراکسی کنفیگریشن کو ایک مسئلہ درپیش آیا!',
        error_desktop_not_supported: 'ڈیسک ٹاپ ماحول سپورٹ نہیں کرتا!',
        error_configuration_not_supported:
            'پراکسی کنفیگریشن آپ کے آپریٹنگ سسٹم میں سپورٹ نہیں کرتا، لیکن آپ وارپ پراکسی کو دستی طور پر استعمال کر سکتے ہیں۔',
        error_configuring_proxy: (value) => `${value} کے لیے پراکسی کنفیگریشن میں مسئلہ!`,
        error_wp_not_found: 'وارپ پلس فائل ایپلیکیشن پیکیج کے ساتھ موجود نہیں ہے!',
        error_mp_not_found: 'masque-plus فائل ایپلیکیشن پیکیج کے ساتھ موجود نہیں ہے!',
        error_usque_not_found: 'usque فائل ایپلیکیشن پیکیج کے ساتھ موجود نہیں ہے!',
        error_wp_exclusions:
            'ممکن ہے کہ وارپ پلس فائل کو ایک جھوٹے مثبت نوٹیفکیشن اور اینٹی وائرس کی غلط شناخت کی وجہ سے قرنطینہ کیا گیا ہو، جس سے پروگرام کی انٹرنیٹ تک آزاد رسائی میں مسائل پیدا ہو گئے ہوں۔\nپروگرام اگر اجازت دی جائے تو اس فائل کو کچھ اینٹی وائرسز میں استثنیات کی فہرست میں شامل کر سکتا ہے۔ کیا یہ عمل کیا جائے؟',
        error_wp_stopped: 'وارپ پلس فائل چلنے کے دوران مسئلہ پیدا ہوا!',
        error_connection_failed: '1.1.1.1 سے کنیکشن ممکن نہیں تھا۔',
        error_country_failed: 'منتخب شدہ ملک سے کنیکٹ نہیں ہو سکتا۔',
        error_singbox_failed_stop: 'سنگ باکس کو روکنے میں ناکامی!',
        error_singbox_failed_start: 'سنگ باکس کو شروع کرنے میں ناکامی!',
        error_wp_reset_peer: 'کلاؤڈفلئیر سے کنیکشن غیر متوقع طور پر منقطع ہو گیا!',
        error_failed_connection: 'کنکشن قائم کرنے میں ناکامی!',
        error_canceled_by_user: 'عملیہ صارف کے ذریعہ منسوخ کر دیا گیا۔',
        error_helper_not_found: 'مددگار فائل ایپلیکیشن پیکیج کے ساتھ موجود نہیں!',
        error_singbox_ipv6_address:
            'آپریٹنگ سسٹم IPv6 کو سپورٹ نہیں کرتا۔ براہ کرم ٹنل سیٹنگز پر جائیں اور ایڈریسنگ کو IPv4 پر تبدیل کریں۔',
        error_local_date: 'یقین دہانی کریں کہ آپ کے سسٹم کی تاریخ اور وقت درست سیٹ کیے گئے ہیں!'
    },
    about: {
        title: 'ایپ کے بارے میں',
        desc: 'یہ پروگرام اوبلیویئن ایپ کا غیر رسمی لیکن قابل اعتماد ورژن ہے جو ونڈوز، لینکس، اور میک کے لیے دستیاب ہے۔\nاوبلیویئن ڈیسک ٹاپ پروگرام کی صارف انٹرفیس کو ماڈل کیا گیا ہے جو یوسف غبادی کے تیار کردہ اصل ورژن پر مبنی ہے۔ یہ مفت انٹرنیٹ تک رسائی کے مقصد کے لیے تیار کیا گیا تھا، اور اس میں کسی قسم کی نام کی تبدیلی یا تجارتی استعمال کی اجازت نہیں ہے۔',
        slogan: 'انٹرنیٹ، سب کے لیے یا کسی کے لیے نہیں!'
    },
    systemTray: {
        connect: 'کنیکٹ',
        connecting: 'کنیکٹ ہو رہا ہے ...',
        connected: 'کنیکٹڈ',
        disconnecting: 'ڈسکنیکٹ ہو رہا ہے ...',
        settings: 'سیٹنگز',
        settings_warp: 'وارپ',
        settings_network: 'نیٹ ورک',
        settings_scanner: 'سکینر',
        settings_app: 'ایپلیکیشن',
        about: 'ایپ کے بارے میں',
        log: 'لاگ',
        speed_test: 'اسپیڈ ٹیسٹ',
        exit: 'باہر نکلیں'
    },
    update: {
        available: 'اپڈیٹ دستیاب ہے',
        available_message: (value) =>
            `نیا ورژن ${value} دستیاب ہے۔ کیا آپ ابھی اپڈیٹ کرنا چاہتے ہیں؟`,
        ready: 'اپڈیٹ تیار ہے',
        ready_message: (value) =>
            `نیا ورژن ${value} تیار ہے۔ یہ ری اسٹارٹ کے بعد انسٹال ہو جائے گا۔ کیا آپ ابھی ری اسٹارٹ کرنا چاہتے ہیں؟`
    },
    speedTest: {
        title: 'اسپیڈ ٹیسٹ',
        initializing: 'اسپیڈ ٹیسٹ شروع ہو رہا ہے ...',
        click_start: 'اسپیڈ ٹیسٹ شروع کرنے کے لیے بٹن پر کلک کریں',
        error_msg: 'اسپیڈ ٹیسٹ کے دوران ایک مسئلہ پیش آیا۔ براہ کرم دوبارہ کوشش کریں۔',
        server_unavailable: 'اسپیڈ ٹیسٹ سرور دستیاب نہیں',
        download_speed: 'ڈاؤنلوڈ اسپیڈ',
        upload_speed: 'اپلوڈ اسپیڈ',
        latency: 'لیٹنسی',
        jitter: 'جٹر'
    }
};
export default urdu;
